### ISSUE TITLE
Cannot get multicast to work

### ISSUE THREAD

**Issue by Asmod4n** [iij/mruby-socket#33]
Am trying to do UDP Multicasting like its done in https://github.com/peteforde/ruby-multicast
But cannot get it to work, any hints? Or is something missing?

**Comment by tsahara** [comment]
Which operating system did you try it on?  I found an issue https://github.com/iij/mruby-socket/issues/34 on BSD systems to fail `sock.setsockopt(Socket::IPPROTO_IP, Socket::IP_MULTICAST_TTL, 1)`.  As a workaround, the line can be commented out since default value of TTL is 1.

And `#setsockopt` on mruby-socket does not accept symbols for 1st and 2nd arguments currently.  They should be constants defined under `Socket` class (e.g. `:IPPROTO_IP` -> `Socket::IPPROTO_IP`).

**Comment by Asmod4n** [comment]
It fails at the part where i try to to ```#setsockopt``` with Socket::IP_ADD_MEMBERSHIP, it seams to do nothing.

**Comment by Asmod4n** [comment]
Found the issue, you always have to bind before you add a membership, and the bind address must always be 0.0.0.0.
